// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes apiKeyAuthContextKey = "ApiKeyAuth.Scopes"
)

// ApiError defines model for ApiError.
type ApiError struct {
	Error string `json:"error"`
}

// Note defines model for Note.
type Note struct {
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
	Id        int64     `json:"id"`
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updated_at"`
}

// NoteRequest defines model for NoteRequest.
type NoteRequest struct {
	Content string `json:"content"`
	Title   string `json:"title"`
}

// apiKeyAuthContextKey is the context key for ApiKeyAuth security scheme
type apiKeyAuthContextKey string

// NotesCreateJSONRequestBody defines body for NotesCreate for application/json ContentType.
type NotesCreateJSONRequestBody = NoteRequest

// NotesUpdateJSONRequestBody defines body for NotesUpdate for application/json ContentType.
type NotesUpdateJSONRequestBody = NoteRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/v1/notes)
	NotesList(c *gin.Context)

	// (POST /api/v1/notes)
	NotesCreate(c *gin.Context)

	// (DELETE /api/v1/notes/{id})
	NotesDelete(c *gin.Context, id int64)

	// (GET /api/v1/notes/{id})
	NotesRead(c *gin.Context, id int64)

	// (PUT /api/v1/notes/{id})
	NotesUpdate(c *gin.Context, id int64)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// NotesList operation middleware
func (siw *ServerInterfaceWrapper) NotesList(c *gin.Context) {

	c.Set(string(ApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.NotesList(c)
}

// NotesCreate operation middleware
func (siw *ServerInterfaceWrapper) NotesCreate(c *gin.Context) {

	c.Set(string(ApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.NotesCreate(c)
}

// NotesDelete operation middleware
func (siw *ServerInterfaceWrapper) NotesDelete(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(ApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.NotesDelete(c, id)
}

// NotesRead operation middleware
func (siw *ServerInterfaceWrapper) NotesRead(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(ApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.NotesRead(c, id)
}

// NotesUpdate operation middleware
func (siw *ServerInterfaceWrapper) NotesUpdate(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(ApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.NotesUpdate(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/v1/notes", wrapper.NotesList)
	router.POST(options.BaseURL+"/api/v1/notes", wrapper.NotesCreate)
	router.DELETE(options.BaseURL+"/api/v1/notes/:id", wrapper.NotesDelete)
	router.GET(options.BaseURL+"/api/v1/notes/:id", wrapper.NotesRead)
	router.PUT(options.BaseURL+"/api/v1/notes/:id", wrapper.NotesUpdate)
}

type NotesListRequestObject struct {
}

type NotesListResponseObject interface {
	VisitNotesListResponse(w http.ResponseWriter) error
}

type NotesList200JSONResponse []Note

func (response NotesList200JSONResponse) VisitNotesListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type NotesListdefaultJSONResponse struct {
	Body       ApiError
	StatusCode int
}

func (response NotesListdefaultJSONResponse) VisitNotesListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type NotesCreateRequestObject struct {
	Body *NotesCreateJSONRequestBody
}

type NotesCreateResponseObject interface {
	VisitNotesCreateResponse(w http.ResponseWriter) error
}

type NotesCreate200JSONResponse Note

func (response NotesCreate200JSONResponse) VisitNotesCreateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type NotesCreatedefaultJSONResponse struct {
	Body       ApiError
	StatusCode int
}

func (response NotesCreatedefaultJSONResponse) VisitNotesCreateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type NotesDeleteRequestObject struct {
	Id int64 `json:"id"`
}

type NotesDeleteResponseObject interface {
	VisitNotesDeleteResponse(w http.ResponseWriter) error
}

type NotesDelete204Response struct {
}

func (response NotesDelete204Response) VisitNotesDeleteResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type NotesDeletedefaultJSONResponse struct {
	Body       ApiError
	StatusCode int
}

func (response NotesDeletedefaultJSONResponse) VisitNotesDeleteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type NotesReadRequestObject struct {
	Id int64 `json:"id"`
}

type NotesReadResponseObject interface {
	VisitNotesReadResponse(w http.ResponseWriter) error
}

type NotesRead200JSONResponse Note

func (response NotesRead200JSONResponse) VisitNotesReadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type NotesReaddefaultJSONResponse struct {
	Body       ApiError
	StatusCode int
}

func (response NotesReaddefaultJSONResponse) VisitNotesReadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type NotesUpdateRequestObject struct {
	Id   int64 `json:"id"`
	Body *NotesUpdateJSONRequestBody
}

type NotesUpdateResponseObject interface {
	VisitNotesUpdateResponse(w http.ResponseWriter) error
}

type NotesUpdate200JSONResponse Note

func (response NotesUpdate200JSONResponse) VisitNotesUpdateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type NotesUpdatedefaultJSONResponse struct {
	Body       ApiError
	StatusCode int
}

func (response NotesUpdatedefaultJSONResponse) VisitNotesUpdateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /api/v1/notes)
	NotesList(ctx context.Context, request NotesListRequestObject) (NotesListResponseObject, error)

	// (POST /api/v1/notes)
	NotesCreate(ctx context.Context, request NotesCreateRequestObject) (NotesCreateResponseObject, error)

	// (DELETE /api/v1/notes/{id})
	NotesDelete(ctx context.Context, request NotesDeleteRequestObject) (NotesDeleteResponseObject, error)

	// (GET /api/v1/notes/{id})
	NotesRead(ctx context.Context, request NotesReadRequestObject) (NotesReadResponseObject, error)

	// (PUT /api/v1/notes/{id})
	NotesUpdate(ctx context.Context, request NotesUpdateRequestObject) (NotesUpdateResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// NotesList operation middleware
func (sh *strictHandler) NotesList(ctx *gin.Context) {
	var request NotesListRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.NotesList(ctx, request.(NotesListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "NotesList")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(NotesListResponseObject); ok {
		if err := validResponse.VisitNotesListResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// NotesCreate operation middleware
func (sh *strictHandler) NotesCreate(ctx *gin.Context) {
	var request NotesCreateRequestObject

	var body NotesCreateJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.NotesCreate(ctx, request.(NotesCreateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "NotesCreate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(NotesCreateResponseObject); ok {
		if err := validResponse.VisitNotesCreateResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// NotesDelete operation middleware
func (sh *strictHandler) NotesDelete(ctx *gin.Context, id int64) {
	var request NotesDeleteRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.NotesDelete(ctx, request.(NotesDeleteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "NotesDelete")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(NotesDeleteResponseObject); ok {
		if err := validResponse.VisitNotesDeleteResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// NotesRead operation middleware
func (sh *strictHandler) NotesRead(ctx *gin.Context, id int64) {
	var request NotesReadRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.NotesRead(ctx, request.(NotesReadRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "NotesRead")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(NotesReadResponseObject); ok {
		if err := validResponse.VisitNotesReadResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// NotesUpdate operation middleware
func (sh *strictHandler) NotesUpdate(ctx *gin.Context, id int64) {
	var request NotesUpdateRequestObject

	request.Id = id

	var body NotesUpdateJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.NotesUpdate(ctx, request.(NotesUpdateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "NotesUpdate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(NotesUpdateResponseObject); ok {
		if err := validResponse.VisitNotesUpdateResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
